services:
  - type: web
    name: shore-store-backend
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 2121
      - key: MONGO_URI
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: SESSION_SECRET
        generateValue: true

  - type: web
    name: shore-store-frontend
    env: docker
    dockerfilePath: frontend/Dockerfile
    dockerContext: frontend
    plan: free
